version: "3"
services:
    frontend:
        image: se2team8/pulsebs-team8:v0
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./client:/app
             -/app/node_modules
        stdin_open: true
        tty: true
        links:
            - backend
    backend:
        image: se2team8/pulsebs-team8:backendv0
        build:
            context: ./server
            dockerfile: Dockerfile
        volumes:
            - ./server:/app
            - /app/node_modules
